/// Every `#[tauri::command]` registered in `lib.rs::commands` (`generate_handler!`).
/// tauri-build turns each into an `allow-<command>` / `deny-<command>` app permission
/// (written to the gitignored `permissions/autogenerated/`) and, because the app now has an
/// `__app__` ACL manifest, tauri 2.12.1 checks every app command against the capabilities:
/// a command is invoked only from a window whose label a capability grants its
/// `allow-<command>` (`capabilities/default.json` → `settings`, `capabilities/overlay.json` →
/// `overlay`); a command missing here is refused from every window (T-049,
/// docs/decisions/ipc-acl.md). `scripts/ci/app-acl.sh` (`make check-app-acl`) keeps this
/// list, `generate_handler!` and the capability grants equal.
const APP_COMMANDS: [&str; 11] = [
    "get_build_info",
    "settings_get",
    "settings_save",
    "settings_speech_languages",
    "settings_list_microphones",
    "settings_test_connection",
    "local_models_list",
    "local_model_download",
    "local_model_cancel_download",
    "local_model_delete",
    "overlay_ready",
];

fn main() {
    let attributes = tauri_build::Attributes::new()
        .app_manifest(tauri_build::AppManifest::new().commands(&APP_COMMANDS));
    if let Err(error) = tauri_build::try_build(attributes) {
        // Same outcome as tauri_build::build(): the build stops with tauri-build's message
        // (e.g. a capability naming a permission that does not exist).
        panic!("tauri-build failed: {error:#}");
    }
    embed_manifest_for_tests();
}

/// Gives every `tests/*.rs` integration-test exe the Common-Controls v6 manifest that
/// tauri-build embeds only into bin targets (F-002, T-035; docs/decisions/ci-toolchain.md).
/// Without it a test exe that creates a tauri app binds comctl32 v5.82 and exits
/// `0xc0000139` `STATUS_ENTRYPOINT_NOT_FOUND` (muda's `TaskDialogIndirect`) before any test runs.
/// `rustc-link-arg-tests` reaches integration tests only, so the release bin keeps
/// tauri-build's manifest unchanged. `windows-app-manifest.xml` is a copy of tauri-build
/// 2.7.1's `src/windows-app-manifest.xml` (same elements and values; comments and whitespace
/// differ); compare it with tauri-build's file on every tauri-build upgrade.
fn embed_manifest_for_tests() {
    let target_os = std::env::var("CARGO_CFG_TARGET_OS").unwrap_or_default();
    let target_env = std::env::var("CARGO_CFG_TARGET_ENV").unwrap_or_default();
    if target_os != "windows" || target_env != "msvc" {
        return;
    }
    // Cargo sets it for every build-script run; without it the linker input is unknown.
    let Some(dir) = std::env::var_os("CARGO_MANIFEST_DIR") else {
        panic!("CARGO_MANIFEST_DIR is not set; cannot locate windows-app-manifest.xml");
    };
    let manifest = std::path::Path::new(&dir).join("windows-app-manifest.xml");
    println!("cargo:rerun-if-changed=windows-app-manifest.xml");
    println!("cargo:rustc-link-arg-tests=/MANIFEST:EMBED");
    println!(
        "cargo:rustc-link-arg-tests=/MANIFESTINPUT:{}",
        manifest.display()
    );
}
