#!/usr/bin/env bash
# T-049 (class ipc-acl; option A, decisions #45, #57): the app commands are ACL-checked per
# window label. tauri 2.12.1 checks a local-origin #[tauri::command] only when the app has an
# '__app__' ACL manifest (tauri-build adds it from AppManifest::commands); then every command
# without a granted allow-<command> is refused at run time, on Windows only, and a command
# missing from the manifest does not fail the build. This Linux tripwire keeps the four lists
# that must agree equal, so a forgotten entry is caught before a Windows CI round:
#   C  the #[tauri::command] fn names under <shell>/src (comments and strings dropped first);
#   H  the names in generate_handler![..] under <shell>/src (last path segment);
#   A  the string entries of `APP_COMMANDS` in <shell>/build.rs;
#   G  the app permissions (an id without ':') granted by <shell>/capabilities/*.json, as
#      commands (allow-local-models-list -> local_models_list).
# This check fails (exit 1, every violation listed) when:
#   1. C != H (a command defined but not registered, or registered but not a command);
#   2. build.rs has no `APP_COMMANDS` array, or does not hand it to tauri-build: no
#      `.app_manifest(` call or no `.commands(&APP_COMMANDS)`;
#   3. A != H (a registered command with no permission, or a permission with no command);
#   4. a registered command is granted by no capability, or a capability grants an app
#      permission whose command is not registered (an orphan grant);
#   5. a capability names an app `deny-*` (a deny ignores window labels, tauri authority.rs)
#      or an app permission that is not `allow-<command>` (a set from a permissions file);
#   6. a capability granting an app permission names a window or webview pattern with `*`,
#      or has a `remote` context (the grant must be per label, local only);
#   7. tauri.conf.json defines capabilities inline (app.security.capabilities), or a file
#      exists under <shell>/permissions outside autogenerated/ (option A: tauri-build writes
#      autogenerated/ from APP_COMMANDS; nothing hand-written that this check does not read);
#   8. a capability file is not valid JSON or has no `permissions` array.
# Not caught: which label gets which command (src-tauri/tests/app_acl.rs, Windows CI);
# a command attribute spelled other than #[tauri::command..] (e.g. `use tauri::command`).
#
# Usage: scripts/ci/app-acl.sh [shell-dir]   (default src-tauri)
# Exit 0: ok. Exit 1: a violation (listed). Exit 3: cannot run (a dir or python3 missing);
# never reported as a pass.
set -uo pipefail
root="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
cd "$root" || exit 3
shell="${1:-src-tauri}"
cannot_run() { echo "app-acl: cannot run: $1" >&2; exit 3; }
[ -d "$shell/src" ] && [ -r "$shell/src" ] || cannot_run "$shell/src not found or not readable"
[ -d "$shell/capabilities" ] || cannot_run "$shell/capabilities not found"
[ -f "$shell/build.rs" ] || cannot_run "$shell/build.rs not found"
command -v python3 >/dev/null 2>&1 || cannot_run "python3 not found"

python3 -I - "$shell" <<'PY'
import glob, json, os, re, sys

shell = sys.argv[1]

def cannot_run(msg):
    print(f"app-acl: cannot run: {msg}", file=sys.stderr)
    sys.exit(3)

def read(path):
    try:
        with open(path, encoding="utf-8") as f:
            return f.read()
    except OSError as e:
        cannot_run(f"cannot read {path}: {e.strerror}")

def strip_rust(text):
    """Drops comments (line, nested block) and the contents of string/char literals,
    keeping string delimiters, so code text inside them never counts."""
    out, i, n = [], 0, len(text)
    while i < n:
        c = text[i]
        if text.startswith("//", i):
            j = text.find("\n", i)
            i = n if j < 0 else j
        elif text.startswith("/*", i):
            depth, i = 1, i + 2
            while i < n and depth:
                if text.startswith("/*", i):
                    depth, i = depth + 1, i + 2
                elif text.startswith("*/", i):
                    depth, i = depth - 1, i + 2
                else:
                    i += 1
        elif c == '"' or (c == "r" and re.match(r'r#*"', text[i:]) and (i == 0 or not (text[i-1].isalnum() or text[i-1] == "_"))):
            m = re.match(r'r(#*)"', text[i:])
            if m:
                end = '"' + m.group(1)
                j = text.find(end, i + len(m.group(0)))
                j = n if j < 0 else j + len(end)
            else:
                j = i + 1
                while j < n and text[j] != '"':
                    j += 2 if text[j] == "\\" else 1
                j += 1
            out.append('""')
            i = j
        elif c == "'":
            m = re.match(r"'(\\.[^']*|[^\\'])'", text[i:])
            if m:
                out.append("''")
                i += len(m.group(0))
            else:  # a lifetime
                out.append(c)
                i += 1
        else:
            out.append(c)
            i += 1
    return "".join(out)

def strings(text):
    """The string literals of `text` (comments dropped)."""
    no_comments = re.sub(r"//[^\n]*", "", text)
    return re.findall(r'"((?:[^"\\]|\\.)*)"', no_comments)

violations = []

# C and H
cmd_re = re.compile(
    r"#\s*\[\s*tauri\s*::\s*command\b[^\]]*\]\s*"
    r"(?:#\s*\[[^\]]*\]\s*)*"
    r"(?:pub\s*(?:\([^)]*\)\s*)?)?(?:async\s+)?(?:unsafe\s+)?fn\s+([A-Za-z_][A-Za-z0-9_]*)"
)
attr_re = re.compile(r"#\s*\[\s*tauri\s*::\s*command\b")
handler_re = re.compile(r"generate_handler\s*!\s*\[(.*?)\]", re.S)
commands, handler = {}, {}
for path in sorted(glob.glob(os.path.join(shell, "src", "**", "*.rs"), recursive=True)):
    code = strip_rust(read(path))
    found = cmd_re.findall(code)
    if len(found) != len(attr_re.findall(code)):
        violations.append(f"{path}: a #[tauri::command] attribute not followed by a fn this check reads")
    for name in found:
        commands.setdefault(name, path)
    for body in handler_re.findall(code):
        for entry in body.split(","):
            entry = re.sub(r"\s+", "", entry)
            if entry:
                handler.setdefault(entry.split("::")[-1], path)

for name in sorted(set(commands) - set(handler)):
    violations.append(f"{commands[name]}: #[tauri::command] {name} is not in generate_handler!")
for name in sorted(set(handler) - set(commands)):
    violations.append(f"{handler[name]}: generate_handler! names {name}, which is no #[tauri::command] under {shell}/src")

# A
build_path = os.path.join(shell, "build.rs")
build = read(build_path)
build_code = strip_rust(build)
m = re.search(r"\bAPP_COMMANDS\s*:[^=]*=\s*&?\s*\[(.*?)\]\s*;", re.sub(r"//[^\n]*", "", build), re.S)
app_commands = None
if not m:
    violations.append(f"{build_path}: no `APP_COMMANDS` array (the app commands tauri-build turns into allow-*/deny-* permissions)")
else:
    app_commands = strings(m.group(1))
    if not re.search(r"\.\s*app_manifest\s*\(", build_code):
        violations.append(f"{build_path}: no `.app_manifest(..)`: APP_COMMANDS never reaches tauri-build (no '__app__' ACL, no app command is checked)")
    if not re.search(r"\.\s*commands\s*\(\s*&?\s*APP_COMMANDS\s*\)", build_code):
        violations.append(f"{build_path}: no `.commands(&APP_COMMANDS)`: the manifest is not built from APP_COMMANDS")
    dups = sorted({c for c in app_commands if app_commands.count(c) > 1})
    for c in dups:
        violations.append(f"{build_path}: APP_COMMANDS names {c} twice")
    for c in sorted(set(handler) - set(app_commands)):
        violations.append(f"{build_path}: registered command {c} is not in APP_COMMANDS (no permission: refused from every window)")
    for c in sorted(set(app_commands) - set(handler)):
        violations.append(f"{build_path}: APP_COMMANDS names {c}, which generate_handler! does not register")

# G
granted = {}
cap_files = sorted(glob.glob(os.path.join(shell, "capabilities", "*.json")))
for path in cap_files:
    try:
        cap = json.loads(read(path))
    except ValueError as e:
        violations.append(f"{path}: not valid JSON ({e})")
        continue
    perms = cap.get("permissions") if isinstance(cap, dict) else None
    if not isinstance(perms, list):
        violations.append(f"{path}: no `permissions` array")
        continue
    app_ids = []
    for p in perms:
        ident = p.get("identifier") if isinstance(p, dict) else p
        if not isinstance(ident, str):
            violations.append(f"{path}: a permission entry without a string identifier: {p!r}")
            continue
        if ":" in ident:
            continue
        app_ids.append(ident)
        if ident.startswith("deny-"):
            violations.append(f"{path}: app permission {ident}: a deny ignores window labels; grant allow-* per label instead")
        elif ident.startswith("allow-") and len(ident) > len("allow-"):
            granted.setdefault(ident[len("allow-"):].replace("-", "_"), []).append(path)
        else:
            violations.append(f"{path}: app permission {ident} is not allow-<command> (option A: one allow-* per command)")
    if app_ids:
        for key in ("windows", "webviews"):
            for pattern in cap.get(key) or []:
                if not isinstance(pattern, str) or "*" in pattern:
                    violations.append(f"{path}: grants app permissions to {key} pattern {pattern!r}; name labels exactly")
        if cap.get("remote"):
            violations.append(f"{path}: grants app permissions to a remote context")

for c in sorted(set(handler) - set(granted)):
    violations.append(f"{shell}/capabilities: registered command {c} is granted to no window (allow-{c.replace('_', '-')})")
for c in sorted(set(granted) - set(handler)):
    violations.append(f"{', '.join(granted[c])}: grants allow-{c.replace('_', '-')}, but no registered command {c} exists")

# 7
conf_path = os.path.join(shell, "tauri.conf.json")
if os.path.exists(conf_path):
    try:
        conf = json.loads(read(conf_path))
    except ValueError as e:
        violations.append(f"{conf_path}: not valid JSON ({e})")
        conf = {}
    sec = ((conf.get("app") or {}).get("security") or {}) if isinstance(conf, dict) else {}
    for c in sec.get("capabilities") or []:
        if not isinstance(c, str):
            violations.append(f"{conf_path}: an inline capability in app.security.capabilities (keep capabilities in {shell}/capabilities)")
perm_dir = os.path.join(shell, "permissions")
for dirpath, _dirs, files in os.walk(perm_dir):
    rel = os.path.relpath(dirpath, perm_dir)
    if rel == "autogenerated" or rel.startswith("autogenerated" + os.sep):
        continue
    for f in files:
        violations.append(f"{os.path.join(dirpath, f)}: a hand-written permission file (option A: permissions come only from APP_COMMANDS)")

if violations:
    print("app-acl: FAIL: every #[tauri::command] must be registered, listed in build.rs APP_COMMANDS")
    print("(tauri-build's AppManifest::commands) and granted as allow-<command> to exact window labels in")
    print(f"{shell}/capabilities, with no deny-* (T-049, decisions #45, #57):")
    for v in violations:
        print(f"  {v}")
    sys.exit(1)
print(f"app-acl: ok: {len(handler)} app commands registered, in APP_COMMANDS and granted ({len(cap_files)} capability files)")
PY
