#!/usr/bin/env bash
# T-077 (decisions #98): host test of scripts/ci/version-stamp.sh, the one place CI computes and
# writes the build version before the windows job's first compile. Contract, pinned here:
#   Usage: scripts/ci/version-stamp.sh <ref_type> <ref_name> <run_number> [root]   (root: ".")
#   Reads [workspace.package] version of <root>/Cargo.toml and the top-level "version" of
#   <root>/src-tauri/tauri.conf.json and <root>/package.json; all three equal and X.Y.Z (no
#   leading zeros), else exit 1 naming the file and the value.
#   ref_type=tag: ref_name must be vX.Y.Z (no leading zeros, each part <= 65535), else exit 1
#   naming the tag; V = X.Y.Z (the run number is not used).
#   Otherwise V = <repo MAJOR>.<repo MINOR>.<run_number>, run_number [1-9][0-9]* and <= 65535,
#   else exit 1 naming the value.
#   Writes V into the three fields and the version of the two workspace members of
#   <root>/Cargo.lock ([[package]] voicen and voicen-core, no source line), no other line; prints
#   "version: V"; appends "VOICEN_VERSION=V" to $GITHUB_ENV when it is set. On exit 1 nothing is
#   written (the tree and $GITHUB_ENV are byte-identical).
# Cases: branch run 58 and 65535 on a fixture tree whose files carry decoy version lines (the
# whole tree must equal the expected tree); tag v1.2.3 (run number ignored); GITHUB_ENV unset;
# bad tags, bad repo versions, the three files disagreeing, bad run numbers (exit 1, the value
# named, tree and GITHUB_ENV unchanged); a copy of the real repo's three files plus Cargo.lock.
# Usage: scripts/ci/version-stamp.test.sh   (host bash, diff, awk)
# Exit 0: every case as expected. Exit 1: a case differs (listed), or the script is missing.
# Exit 3: cannot run.
set -uo pipefail
root="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
cd "$root" || exit 3
script="$root/scripts/ci/version-stamp.sh"
if [ ! -x "$script" ]; then
  echo "version-stamp.test: FAIL: $script not found or not executable" >&2
  exit 1
fi
tmp="$(mktemp -d)" || { echo "version-stamp.test: cannot run: mktemp failed" >&2; exit 3; }
trap 'rm -rf "$tmp"' EXIT

# mk_tree <dir> <cargo ver> <tauri ver> <package ver> <lock ver>: a fixture tree. Every file
# carries decoy "version" lines that must never change (some with the same value 0.1.0, some
# placed before the real field).
mk_tree() {
  local d="$1" cv="$2" tv="$3" pv="$4" lv="$5"
  mkdir -p "$d/src-tauri"
  cat > "$d/Cargo.toml" <<EOF
[workspace]
members = ["crates/voicen-core", "src-tauri"]
resolver = "2"

[workspace.metadata.decoy]
version = "0.1.0"

[workspace.package]
version = "$cv"
edition = "2021"
license = "MIT"

[workspace.dependencies]
serde = { version = "0.1.0", features = ["derive"] }

[profile.release]
lto = true
EOF
  cat > "$d/src-tauri/tauri.conf.json" <<EOF
{
  "\$schema": "https://schema.tauri.app/config/2",
  "decoy": {
    "version": "0.1.0"
  },
  "productName": "Voicen",
  "version": "$tv",
  "plugins": {
    "updater": { "version": "0.1.0" }
  }
}
EOF
  cat > "$d/package.json" <<EOF
{
  "name": "voicen",
  "config": {
    "version": "0.1.0"
  },
  "version": "$pv",
  "dependencies": {
    "decoy": "0.1.0"
  }
}
EOF
  cat > "$d/Cargo.lock" <<EOF
# This file is automatically @generated by Cargo.
# It is not intended for manual editing.
version = 4

[[package]]
name = "serde"
version = "0.1.0"
source = "registry+https://github.com/rust-lang/crates.io-index"
checksum = "0000000000000000000000000000000000000000000000000000000000000000"

[[package]]
name = "voicen"
version = "$lv"
dependencies = [
 "serde",
 "voicen-core",
]

[[package]]
name = "voicen-core"
version = "$lv"
dependencies = [
 "serde",
]

[[package]]
name = "voicen-decoy"
version = "0.1.0"
source = "registry+https://github.com/rust-lang/crates.io-index"
checksum = "1111111111111111111111111111111111111111111111111111111111111111"
EOF
}

failed=0
passed=0
fail() { echo "FAIL $label: $1" >&2; sed 's/^/       | /' <<<"$out" >&2; failed=$((failed + 1)); ok=0; }
done_case() { [ "$ok" = 1 ] && { echo "ok   $label"; passed=$((passed + 1)); }; }

# run <label> <tree dir> <args...>: runs the script on the tree with GITHUB_ENV=$tmp/env (one
# pre-existing line); sets out/rc. The tree is the 4th argument the caller passes.
run() {
  label="$1"; ok=1
  shift
  printf 'OTHER=keep\n' > "$tmp/env"
  out="$(GITHUB_ENV="$tmp/env" "$script" "$@" 2>&1)"
  rc=$?
}
want_rc() { [ "$rc" = "$1" ] || fail "exit $rc, want $1"; }
want_line() { grep -qxF -- "$1" <<<"$out" || fail "output lacks the line: $1"; }
names() { grep -qF -- "$1" <<<"$out" || fail "the output does not name $2"; }
same_tree() { diff -r "$1" "$2" > "$tmp/diff" 2>&1 || { fail "tree differs from $3: $(head -20 "$tmp/diff" | tr '\n' ' ')"; }; }
env_is() {
  local want
  want="$(printf '%s' "$1")"
  [ "$(cat "$tmp/env")" = "$want" ] || fail "GITHUB_ENV is '$(tr '\n' '|' < "$tmp/env")', want '$(tr '\n' '|' <<<"$want")'"
}

# ---- good inputs ---------------------------------------------------------------------------

mk_tree "$tmp/branch" 0.1.0 0.1.0 0.1.0 0.1.0
mk_tree "$tmp/want-58" 0.1.58 0.1.58 0.1.58 0.1.58
run branch-58 branch main 58 "$tmp/branch"
want_rc 0; want_line 'version: 0.1.58'
same_tree "$tmp/want-58" "$tmp/branch" "the expected stamped tree (0.1.58 in five places, decoys kept)"
env_is $'OTHER=keep\nVOICEN_VERSION=0.1.58'
done_case

mk_tree "$tmp/wip" 3.7.0 3.7.0 3.7.0 3.7.0
mk_tree "$tmp/want-max" 3.7.65535 3.7.65535 3.7.65535 3.7.65535
run branch-max-run-number branch wip/T-077 65535 "$tmp/wip"
want_rc 0; want_line 'version: 3.7.65535'
same_tree "$tmp/want-max" "$tmp/wip" "the expected tree (repo MAJOR.MINOR 3.7, run 65535)"
env_is $'OTHER=keep\nVOICEN_VERSION=3.7.65535'
done_case

mk_tree "$tmp/tag" 0.1.0 0.1.0 0.1.0 0.1.0
mk_tree "$tmp/want-tag" 1.2.3 1.2.3 1.2.3 1.2.3
run tag-v1.2.3 tag v1.2.3 58 "$tmp/tag"
want_rc 0; want_line 'version: 1.2.3'
same_tree "$tmp/want-tag" "$tmp/tag" "the expected tree (tag 1.2.3, run number unused)"
env_is $'OTHER=keep\nVOICEN_VERSION=1.2.3'
done_case

# A branch whose name looks like a tag is still a branch build.
mk_tree "$tmp/vbranch" 0.1.0 0.1.0 0.1.0 0.1.0
run branch-named-like-a-tag branch v9.9.9 58 "$tmp/vbranch"
want_rc 0; want_line 'version: 0.1.58'
same_tree "$tmp/want-58" "$tmp/vbranch" "the expected tree (ref_type branch: run number, not the name)"
done_case

mk_tree "$tmp/noenv" 0.1.0 0.1.0 0.1.0 0.1.0
label=no-github-env; ok=1
out="$(cd "$tmp/noenv" && env -u GITHUB_ENV "$script" branch main 58 2>&1)"; rc=$?
want_rc 0; want_line 'version: 0.1.58'
same_tree "$tmp/want-58" "$tmp/noenv" "the expected tree (root defaults to the current directory)"
done_case

# ---- bad inputs: exit 1, the value named, nothing written ----------------------------------

# bad <label> <value it must name> <tree versions: cargo tauri package lock> -- <script args before root>
bad() {
  local lbl="$1" value="$2" cv="$3" tv="$4" pv="$5" lv="$6"
  shift 7
  rm -rf "$tmp/bad" "$tmp/bad-orig"
  mk_tree "$tmp/bad" "$cv" "$tv" "$pv" "$lv"
  mk_tree "$tmp/bad-orig" "$cv" "$tv" "$pv" "$lv"
  run "$lbl" "$@" "$tmp/bad"
  want_rc 1
  names "$value" "the bad value $value"
  same_tree "$tmp/bad-orig" "$tmp/bad" "the untouched tree"
  env_is 'OTHER=keep'
  ! grep -q '^version: ' <<<"$out" || fail "a version line was printed on a refused input"
}

for t in v1.2 vfoo v01.2.3 1.2.3 v1.2.3-rc1 v1.2.3.4 v1.65536.0; do
  bad "tag-$t" "$t" 0.1.0 0.1.0 0.1.0 0.1.0 -- tag "$t" 58
  done_case
done

for v in 0.1 01.1.0 0.1.0-dev x.y.z; do
  bad "repo-version-$v" "$v" "$v" "$v" "$v" "$v" -- branch main 58
  grep -qE -- "(Cargo\.toml|tauri\.conf\.json|package\.json)" <<<"$out" || fail "the output names none of the three files"
  done_case
done

bad mismatch-tauri 0.2.0 0.1.0 0.2.0 0.1.0 0.1.0 -- branch main 58
names tauri.conf.json "the disagreeing file tauri.conf.json"; done_case
bad mismatch-package 0.1.1 0.1.0 0.1.0 0.1.1 0.1.0 -- branch main 58
names package.json "the disagreeing file package.json"; done_case
bad mismatch-cargo 1.1.0 1.1.0 0.1.0 0.1.0 0.1.0 -- tag v1.2.3 58
names Cargo.toml "the disagreeing file Cargo.toml"; done_case

# an empty value cannot be named: the message must name the run number instead
bad run-number-empty "" 0.1.0 0.1.0 0.1.0 0.1.0 -- branch main ''
grep -qiE -- 'run.?number' <<<"$out" || fail "the output does not name the run number"
done_case
for n in 5a 0x3A -1 0 058 65536 99999999999999999999; do
  bad "run-number-$n" "$n" 0.1.0 0.1.0 0.1.0 0.1.0 -- branch main "$n"
  done_case
done

# Fewer than three arguments: refused (non-zero), the current directory's tree unchanged.
rm -rf "$tmp/usage" "$tmp/usage-orig"
mk_tree "$tmp/usage" 0.1.0 0.1.0 0.1.0 0.1.0
mk_tree "$tmp/usage-orig" 0.1.0 0.1.0 0.1.0 0.1.0
label=usage; ok=1
out="$(cd "$tmp/usage" && GITHUB_ENV="$tmp/env" "$script" branch main 2>&1)"; rc=$?
[ "$rc" != 0 ] || fail "exit 0 with two arguments"
same_tree "$tmp/usage-orig" "$tmp/usage" "the untouched tree"
done_case

# ---- the real repository files -------------------------------------------------------------

real="$tmp/real"
mkdir -p "$real/src-tauri"
cp Cargo.toml Cargo.lock package.json "$real/" && cp src-tauri/tauri.conf.json "$real/src-tauri/" ||
  { echo "version-stamp.test: cannot run: cannot copy the repository files" >&2; exit 3; }
cp -r "$real" "$tmp/real-orig"
repo_ver="$(awk '/^\[/{s=($0=="[workspace.package]")} s && /^version *=/{gsub(/.*= *"|".*/,""); print; exit}' Cargo.toml)"
mm="${repo_ver%.*}"
run real-repo branch main 58 "$real"
want_rc 0; want_line "version: $mm.58"
env_is "OTHER=keep"$'\n'"VOICEN_VERSION=$mm.58"
# exactly the version lines change: one per manifest, two in Cargo.lock, each to the new value
for f in Cargo.toml src-tauri/tauri.conf.json package.json Cargo.lock; do
  want_n=1; [ "$f" = Cargo.lock ] && want_n=2
  d="$(diff "$tmp/real-orig/$f" "$real/$f")"
  n_old="$(grep -c '^< ' <<<"$d")"; n_new="$(grep -c '^> ' <<<"$d")"
  [ "$n_old" = "$want_n" ] && [ "$n_new" = "$want_n" ] || fail "$f: $n_old line(s) removed, $n_new added, want $want_n each"
  ! grep '^> ' <<<"$d" | grep -vqE "^> *\"?version\"? *[=:] *\"$mm\.58\",?$" || fail "$f: a changed line is not the version $mm.58: $(grep '^> ' <<<"$d" | tr '\n' ' ')"
  ! grep '^< ' <<<"$d" | grep -vqE "^< *\"?version\"? *[=:] *\"$repo_ver\",?$" || fail "$f: a line other than version $repo_ver was replaced"
done
for pkg in voicen voicen-core; do
  got="$(awk -v p="$pkg" '/^\[\[package\]\]/{n=""} /^name = /{n=$3} n=="\""p"\"" && /^version = /{print $3; exit}' "$real/Cargo.lock")"
  [ "$got" = "\"$mm.58\"" ] || fail "Cargo.lock [[package]] $pkg has version $got, want \"$mm.58\""
done
done_case

if [ "$failed" != 0 ]; then
  echo "version-stamp.test: $failed case(s) failed, $passed ok" >&2
  exit 1
fi
echo "version-stamp.test: ok: $passed cases as expected"
