// Generator of THIRD-PARTY-NOTICES.txt from the cargo-about output, the npm bundle list
// and licenses/manual.json (T-027). Called by `make licenses` / `make licenses-check`.
//
//   node scripts/licenses/notices.mjs --rust target/licenses/rust.txt \
//     --bundle target/licenses/npm-bundled.json --manual licenses/manual.json \
//     --out target/licenses/THIRD-PARTY-NOTICES.txt
//
// Deterministic: no dates, no machine paths, LF line endings, sorted input. Manual-list
// `text` paths are relative to the current directory (the repository root under make).
// Exit 0: written. Exit 2: an input is missing or a package has no license text.
// It does not judge licenses; check.mjs and cargo-about do.
import { readFileSync, readdirSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { pathToFileURL } from "node:url";
import { loadBundleList, readPackageLicense } from "./bundle.mjs";
import { loadManualList, parseArgs } from "./check.mjs";

const RULE = "=".repeat(80);
const LINE = "-".repeat(80);
/** License-text file names in an npm package; .spdx files are metadata, not texts. */
const LICENSE_FILE = /^(licen[cs]e|copying|notice)([.\-_].*)?$/i;

/** LF endings, no trailing blank lines. */
function normalize(/** @type {string} */ text) {
  return text.replace(/\r\n?/g, "\n").replace(/\s+$/, "");
}

function compare(/** @type {string} */ a, /** @type {string} */ b) {
  return a < b ? -1 : a > b ? 1 : 0;
}

function section(/** @type {string} */ title) {
  return [RULE, title, RULE, ""];
}

/** npm `repository` as a URL, or null. */
function repositoryUrl(/** @type {unknown} */ repo) {
  const url = typeof repo === "string" ? repo : repo && typeof repo === "object" && "url" in repo ? repo.url : null;
  return typeof url === "string" ? url.replace(/^git\+/, "") : null;
}

/**
 * The text block of one bundled npm package.
 * @param {{ name: string, version: string, dir: string }} entry
 * @returns {string[]}
 */
function npmBlock(entry) {
  const { name, version, license } = readPackageLicense(entry.dir);
  const pkg = JSON.parse(readFileSync(join(entry.dir, "package.json"), "utf8"));
  const files = readdirSync(entry.dir)
    .filter((f) => LICENSE_FILE.test(f) && !f.toLowerCase().endsWith(".spdx"))
    .sort(compare);
  if (files.length === 0) throw new Error(`npm package ${name}@${version} has no license file; its license text cannot be listed`);
  const url = repositoryUrl(pkg.repository);
  const lines = [LINE, `${name} ${version}`, `License: ${license ?? "(none given)"}`];
  if (url) lines.push(`Source: ${url}`);
  for (const f of files) lines.push("", normalize(readFileSync(join(entry.dir, f), "utf8")));
  lines.push("");
  return lines;
}

/**
 * The text of THIRD-PARTY-NOTICES.txt.
 * @param {{ rustText: string, bundle: { name: string, version: string, dir: string }[], manual: { name: string, version?: string, license?: string | null, url?: string, note?: string, text?: string }[], readText?: (path: string) => string }} input
 * @returns {string}
 */
export function renderNotices({ rustText, bundle, manual, readText = (p) => readFileSync(p, "utf8") }) {
  const out = [
    "THIRD-PARTY NOTICES",
    "",
    "Voicen includes or downloads the third-party components listed below. Each is",
    "listed with its license and the license text.",
    "",
    "Generated by `make licenses` from Cargo.lock (cargo-about, Windows target, normal",
    "dependencies), the client bundle of the user interface and licenses/manual.json.",
    "Do not edit by hand.",
    "",
    ...section("PART 1. Rust crates"),
    normalize(rustText),
    "",
    ...section("PART 2. npm packages in the user interface"),
  ];

  /** @type {Map<string, { name: string, version: string, dir: string }>} */
  const unique = new Map();
  for (const p of bundle) if (!unique.has(`${p.name}@${p.version}`)) unique.set(`${p.name}@${p.version}`, p);
  const packages = [...unique.values()].sort((a, b) => compare(a.name, b.name) || compare(a.version, b.version));
  for (const p of packages) out.push(...npmBlock(p));

  out.push(...section("PART 3. Other components"));
  /** @type {Map<string, string>} text path -> first component printed with it */
  const printed = new Map();
  for (const m of manual) {
    out.push(LINE, m.version ? `${m.name} ${m.version}` : m.name, `License: ${m.license ?? "(none given)"}`);
    if (m.url) out.push(`Source: ${m.url}`);
    if (m.note) out.push(m.note);
    if (m.text) {
      const first = printed.get(m.text);
      if (first) out.push("", `License text: see "${first}" above.`);
      else {
        printed.set(m.text, m.name);
        out.push("", normalize(readText(m.text)));
      }
    }
    out.push("");
  }
  return `${normalize(out.join("\n"))}\n`;
}

/**
 * @param {string[]} argv
 * @returns {number} exit code
 */
export function main(argv) {
  try {
    const args = parseArgs(argv, ["rust", "bundle", "manual", "out"]);
    for (const k of ["rust", "bundle", "manual", "out"]) {
      if (!args[k]) throw new Error(`missing --${k}`);
    }
    let rustText;
    try {
      rustText = readFileSync(args.rust[0], "utf8");
    } catch (e) {
      throw new Error(`cannot read the cargo-about output ${args.rust[0]}: ${e instanceof Error ? e.message : e}`);
    }
    const text = renderNotices({
      rustText,
      bundle: loadBundleList(args.bundle[0]),
      manual: loadManualList(args.manual[0]),
    });
    writeFileSync(args.out[0], text);
    return 0;
  } catch (e) {
    console.error(`licenses: cannot generate THIRD-PARTY-NOTICES.txt: ${e instanceof Error ? e.message : e}`);
    return 2;
  }
}

if (process.argv[1] && import.meta.url === pathToFileURL(process.argv[1]).href) {
  process.exitCode = main(process.argv.slice(2));
}
